# Part 1 (Complete, do not touch)

In [2]:
!pip install transformers evaluate accelerate datasets bert_score rouge_score

Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.50.0)
Collecting evaluate
  Downloading evaluate-0.4.3-py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: accelerate in /usr/local/lib/python3.11/dist-packages (1.5.2)
Collecting datasets
  Downloading datasets-3.5.0-py3-none-any.whl.metadata (19 kB)
Collecting bert_score
  Downloading bert_score-0.3.13-py3-none-any.whl.metadata (15 kB)
Collecting rouge_score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.26.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.29.3)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Collecting dill (from evaluate)
  Downloading dill-0.3.9-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.2.2)
Collecting xxhash (from evaluate)
  Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess (from evaluate)
  Downloading multiprocess-0.70.17-py311-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from accelerate) (2.6.0+cpu)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (19.0.1)
Collecting dill (from evaluate)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Collecting multiprocess (from evaluate)
  Downloading multiprocess-0.70.16-py311-none-any.whl.metadata (7.2 kB)
Collecting fsspec>=2021.05.0 (from fsspec[http]>=2021.05.0->evaluate)
  Downloading fsspec-2024.12.0-py3-none-any.whl.metadata (11 kB)
Collecting aiohttp (from datasets)
  Downloading aiohttp-3.11.14-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.7 kB)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (from bert_score) (3.10.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.11/dist-packages (from rouge_score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.11/dist-packages (from rouge_score) (3.9.1)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.11/dist-packages (from rouge_score) (1.17.0)
Collecting aiohappyeyeballs>=2.3.0 (from aiohttp->datasets)
  Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.1.2 (from aiohttp->datasets)
  Downloading aiosignal-1.3.2-py2.py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (25.3.0)
Collecting frozenlist>=1.1.1 (from aiohttp->datasets)
  Downloading frozenlist-1.5.0-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (6.2.0)
Collecting propcache>=0.2.0 (from aiohttp->datasets)
  Downloading propcache-0.3.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (10 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp->datasets)
  Downloading yarl-1.18.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (69 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.2/69.2 kB 2.1 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.26.0->transformers) (4.12.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2025.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.1.31)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->bert_score) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib->bert_score) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->bert_score) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->bert_score) (1.4.8)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib->bert_score) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->bert_score) (3.2.1)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from nltk->rouge_score) (8.1.8)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from nltk->rouge_score) (1.4.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.2)
Downloading evaluate-0.4.3-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.0/84.0 kB 4.5 MB/s eta 0:00:00
Downloading datasets-3.5.0-py3-none-any.whl (491 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 491.2/491.2 kB 15.7 MB/s eta 0:00:00
Downloading bert_score-0.3.13-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.1/61.1 kB 4.2 MB/s eta 0:00:00
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 8.6 MB/s eta 0:00:00
Downloading fsspec-2024.12.0-py3-none-any.whl (183 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.9/183.9 kB 11.7 MB/s eta 0:00:00
Downloading aiohttp-3.11.14-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 46.8 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py311-none-any.whl (143 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 10.8 MB/s eta 0:00:00
Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 12.8 MB/s eta 0:00:00
Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Downloading aiosignal-1.3.2-py2.py3-none-any.whl (7.6 kB)
Downloading frozenlist-1.5.0-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (274 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 274.9/274.9 kB 18.6 MB/s eta 0:00:00
Downloading propcache-0.3.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (232 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.5/232.5 kB 15.5 MB/s eta 0:00:00
Downloading yarl-1.18.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (344 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 344.1/344.1 kB 21.2 MB/s eta 0:00:00
Building wheels for collected packages: rouge_score
  Building wheel for rouge_score (pyproject.toml) ... done
  Created wheel for rouge_score: filename=rouge_score-0.1.2-py3-none-any.whl size=24986 sha256=489fbb39fd512cf47d04bb808127da68cdacde59279662f93967aa1cbf6b6b37
  Stored in directory: /root/.cache/pip/wheels/1e/19/43/8a442dc83660ca25e163e1bd1f89919284ab0d0c1475475148
Successfully built rouge_score
Installing collected packages: xxhash, propcache, fsspec, frozenlist, dill, aiohappyeyeballs, yarl, rouge_score, multiprocess, aiosignal, aiohttp, datasets, bert_score, evaluate
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.3.0
    Uninstalling fsspec-2025.3.0:
      Successfully uninstalled fsspec-2025.3.0
Successfully installed aiohappyeyeballs-2.6.1 aiohttp-3.11.14 aiosignal-1.3.2 bert_score-0.3.13 datasets-3.5.0 dill-0.3.8 evaluate-0.4.3 frozenlist-1.5.0 fsspec-2024.12.0 multiprocess-0.70.16 propcache-0.3.1 rouge_score-0.1.2 xxhash-3.5.0 yarl-1.18.3

In [3]:
from transformers import AutoTokenizer, AutoModelForCausalLM
import pandas as pd
import evaluate

In [4]:
tokenizer = AutoTokenizer.from_pretrained("gpt2")
model = AutoModelForCausalLM.from_pretrained("gpt2")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

In [5]:
pd.options.display.max_colwidth = 200
perplexity = evaluate.load("perplexity", module_type="metric")

Downloading builder script:   0%|          | 0.00/8.46k [00:00<?, ?B/s]

## Step 1

In [6]:
# Prompt entry
prompts = [
    'A serious and good philosophical work could',
    'The limits of my language means',
    'I don\'t know why we are here, but',
    'The real question of life after death',
    'A man will be imprisoned in a room',
]

In [7]:
# cleans a dictionary for output in pandas dataframe
def format_dict(dict): return '\n'.join(f'{k}: {v}' for k, v in dict.items())

In [8]:
# processes outputs for each algorithm for a given prompt and parameters
def generate_outputs(prompt, parameters):
  max_length = parameters['max_length']
  num_beams = parameters['num_beams']
  top_k = parameters['top_k']
  top_p = parameters['top_p']

  outputs = {}
  perplexities = {}

  input_ids = tokenizer(prompt, return_tensors="pt").input_ids

  # greedy search is the default behavior of model generation
  greedy_outputs = model.generate(input_ids, pad_token_id=tokenizer.eos_token_id, do_sample=False, max_length=max_length)
  # beam search is enabled whenever num_beams is specified above 1
  beam_outputs = model.generate(input_ids, pad_token_id=tokenizer.eos_token_id, do_sample=False, max_length=max_length, num_beams=num_beams)
  # do_sample enables sampling and disables greedy search
  # top_k specifies the number most likely tokens to maintain
  top_k_outputs = model.generate(input_ids, pad_token_id=tokenizer.eos_token_id, do_sample=True, max_length=max_length, top_k=top_k)
  # top_p specifies the cumulative probability threshold that is considered for token selection
  top_p_outputs = model.generate(input_ids, pad_token_id=tokenizer.eos_token_id, do_sample=True, max_length=max_length, top_p=top_p)

  outputs['prompt'] = prompt

  outputs['greedy'] = tokenizer.batch_decode(greedy_outputs, skip_special_tokens=True)
  outputs['beam'] = tokenizer.batch_decode(beam_outputs, skip_special_tokens=True)
  outputs['top k'] = tokenizer.batch_decode(top_k_outputs, skip_special_tokens=True)
  outputs['top p'] = tokenizer.batch_decode(top_p_outputs, skip_special_tokens=True)

  outputs['parameters'] = format_dict(parameters)

  # compute perplexities for each algorithm
  perplexities['greedy'] = perplexity.compute(model_id="gpt2", predictions=outputs['greedy'])['mean_perplexity']
  perplexities['beam'] = perplexity.compute(model_id="gpt2", predictions=outputs['beam'])['mean_perplexity']
  perplexities['top k'] = perplexity.compute(model_id="gpt2", predictions=outputs['top k'])['mean_perplexity']
  perplexities['top p'] = perplexity.compute(model_id="gpt2", predictions=outputs['top p'])['mean_perplexity']

  outputs['perplexity'] = format_dict(perplexities)

  return outputs

In [9]:
# driver function
def compare_algorithms(prompts):
  parameters = {
    'max_length': 30,
    'num_beams': 5,
    'top_k': 50,
    'top_p': 0.95
  }
  rows = []
  for prompt in prompts:
    row = generate_outputs(prompt, parameters)
    rows.append(row)

  results_df = pd.DataFrame(rows)
  return results_df

In [10]:
results = compare_algorithms(prompts)

The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

In [11]:
display(results)

,prompt,greedy,beam,top k,top p,parameters,perplexity
0,A serious and good philosophical work could,[A serious and good philosophical work could be done in the future.\n\nThe first step is to find a way to make the work more accessible to],[A serious and good philosophical work could not have been written without it.\n\nI am not a philosopher. I am not a scientist. I am],"[A serious and good philosophical work could be published in any number of ways. In the early 19th century, William Butler Yeats famously put forward a]","[A serious and good philosophical work could be done within the context of such a project.\n\nHowever, such a project would necessitate a substantial step]",max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 20.087020874023438\nbeam: 12.959490776062012\ntop k: 25.13960838317871\ntop p: 25.614749908447266
1,The limits of my language means,[The limits of my language means that I can't speak it. I can't write it. I can't write it. I can't write it],[The limits of my language means that I don't know what I'm talking about. I don't know what I'm talking about. I don't],[The limits of my language means a certain amount of power is necessary to express his meaning; and it is my duty to say thus about the words and],[The limits of my language means that if you're willing to put yourself in the middle of someone else's problem-solving process then it will be],max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 6.806146144866943\nbeam: 6.083348751068115\ntop k: 37.699424743652344\ntop p: 19.26453399658203
2,"I don't know why we are here, but","[I don't know why we are here, but we are here to help you. We are here to help you. We are here to help you]","[I don't know why we are here, but we are here. We are here. We are here. We are here. We are here.]","[I don't know why we are here, but the game needs to change. It's a matter of time before the game comes to America.""\n]","[I don't know why we are here, but because of this tragedy we have to change our mentality about how to act.\n\n""I can]",max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 4.032037734985352\nbeam: 3.4798924922943115\ntop k: 12.607850074768066\ntop p: 13.887611389160156
3,The real question of life after death,"[The real question of life after death is not whether you will live or die, but whether you will live or die.\n\nThe question of life]","[The real question of life after death is what happens to the body after death, and what happens to the soul after death.\n\nThe question of]","[The real question of life after death is how many children, if any, are born into this world, at least by the time adults die?\n]","[The real question of life after death in this world, then, is whether any of the following might happen, for in all its mysteries of the world]",max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 6.118663311004639\nbeam: 6.55849027633667\ntop k: 15.893404006958008\ntop p: 32.61334228515625
4,A man will be imprisoned in a room,[A man will be imprisoned in a room with a woman for the rest of his life.\n\nThe man will be sentenced to life in prison.],[A man will be imprisoned in a room where he will not be able to speak.\n\nA man will be imprisoned in a room where he will],"[A man will be imprisoned in a room with a small, unmarked manhole. It is important that his release and sentence have the right message: Don]",[A man will be imprisoned in a room for the rest of his life after a hit-and-run crash involving a Porsche 535.\n\n],max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 8.941352844238281\nbeam: 6.350132465362549\ntop k: 57.36750793457031\ntop p: 15.031204223632812

# Part 2

In [12]:
# I figure it'll be useful to do the dataset and model used in the example,
# then if we have issues there's a higher chance the prof/TAs will be familiar

#Loading dataset used in example
from datasets import load_dataset

ds = load_dataset("EdinburghNLP/xsum")

#Loading model used in example
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

tokenizer = AutoTokenizer.from_pretrained("gniemiec/t5-small-finetuned-xsum")
model = AutoModelForSeq2SeqLM.from_pretrained("gniemiec/t5-small-finetuned-xsum")

README.md:   0%|          | 0.00/6.24k [00:00<?, ?B/s]

xsum.py:   0%|          | 0.00/5.76k [00:00<?, ?B/s]

0000.parquet:   0%|          | 0.00/304M [00:00<?, ?B/s]

0000.parquet:   0%|          | 0.00/16.7M [00:00<?, ?B/s]

0000.parquet:   0%|          | 0.00/17.0M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/204045 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/11332 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/11334 [00:00<?, ? examples/s]

tokenizer_config.json:   0%|          | 0.00/1.92k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.39M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/1.79k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.42k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/242M [00:00<?, ?B/s]

In [13]:
documents = ds["test"]["document"][0:50]
#stripping commas to see if this improves performance in any way
for i in range(len(documents)):
  documents[i] = documents[i].replace(',', '')
references = ds["test"]["summary"][0:50]

results = compare_algorithms(documents)
results["references"] = tokenizer.batch_decode(tokenizer(references, return_tensors="pt", padding=True).input_ids, skip_special_tokens=True) # Added padding which seemed to fix errors later on
display(results)

Token indices sequence length is longer than the specified maximum sequence length for this model (744 > 512). Running this sequence through the model will result in indexing errors

model.safetensors:   0%|          | 0.00/242M [00:00<?, ?B/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

,prompt,greedy,beam,top k,top p,parameters,perplexity,references
0,Prison Link Cymru had 1099 referrals in 2015-16 and said some ex-offenders were living rough for up to a year before finding suitable accommodation.\nWorkers at the charity claim investment in hou...,"[in Wales, a charity that has urged people to stay in a secure housing estate has said it is ""chronic"" for]","[in Wales, the Welsh Government has urged people to stay in a secure housing estate.]",[for the next five years and will run into it. who have been targeted by prison force members in Wales has been put in this post],"[to live in a secure apartment in Wales. It's a new, exciting and innovative development to use in housing in South Wales]",max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 46.846336364746094\nbeam: 33.5189094543457\ntop k: 148.06150817871094\ntop p: 58.72018051147461,"There is a ""chronic"" need for more housing for prison leavers in Wales, according to a charity."
1,Officers searched properties in the Waterfront Park and Colonsay View areas of the city on Wednesday.\nDetectives said three firearms ammunition and a five-figure sum of money were recovered.\nA 2...,[Police have recovered three firearms ammunition and a five-figure sum of money.],[Police have recovered three firearms ammunition and a five-figure sum of money.],"[are in custody and have arrested 26-year-old Amarsh Scott, whose family has been forced to return the missing person]",[Police Officers have recovered three firearms ammunition and five-figure sums of money.],max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 41.20834732055664\nbeam: 41.20834732055664\ntop k: 68.57975006103516\ntop p: 87.23341369628906,"A man has appeared in court after firearms, ammunition and cash were seized by police in Edinburgh."
2,Jordan Hill Brittany Covington and Tesfaye Cooper all 18 and Tanishia Covington 24 appeared in a Chicago court on Friday.\nThe four have been charged with hate crimes and aggravated kidnapping and...,"[and,, and have been charged with hate crimes and aggravated kidnapping. and have been]","[who have been charged with hate crimes, aggravated kidnapping and battery among other things.]",[All-American. have been charged with hate crimes and aggravated kidnapping as three assailants are found],"[An Alabama woman who has been sentenced to 21 years in prison is awaiting trial for assaulting his mother, Tim Hill, in ]",max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 60.31381607055664\nbeam: 46.98090362548828\ntop k: 133.20643615722656\ntop p: 39.66783142089844,"Four people accused of kidnapping and torturing a mentally disabled man in a ""racially motivated"" attack streamed on Facebook have been denied bail."
3,The 48-year-old former Arsenal goalkeeper played for the Royals for four years.\nHe was appointed youth academy director in 2000 and has been director of football since 2003.\nA West Brom statemen...,[keeper David West Brom has been appointed a youth academy director of football since 2003.],['s former Arsenal goalkeeper has played for the Royals for four years and has been director of football since 2003.],[goalkeeper David Eldrado spent eight months working in the Athletic Union Division.],[Arsenal goalkeeper Ibrahim Ibrahimovic has been appointed manager of the University of Newcastle United.],max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 209.69117736816406\nbeam: 33.44632339477539\ntop k: 398.7690124511719\ntop p: 36.21345901489258,"West Brom have appointed Nicky Hammond as technical director, ending his 20-year association with Reading."
4,Restoring the function of the organ - which helps control blood sugar levels - reversed symptoms of diabetes in animal experiments.\nThe study published in the journal Cell says the diet reboots t...,"[and. ""The results of the study have been very exciting,"" said Dr James Longo. ""The results of the study have been]","[. ""I was glad to have something to eat"" in a diet that regenerated a cell in the pancrea]","[- in humans - that can be described as ""possibly quite exciting from the end of the day"" in animal experiment results]","[, however, a body is reset to form a new system. In many studies it has a potential to retrain glucose]",max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 20.34456443786621\nbeam: 99.07830810546875\ntop k: 135.201904296875\ntop p: 144.0154571533203,"The pancreas can be triggered to regenerate itself through a type of fasting diet, say US researchers."
5,But there certainly should be.\nThese are two of the biggest firms in the lucrative international business of making spectacles. France's Essilor is the world's number one manufacturer of lenses a...,"[and of optical optical products. and, and and of optical optical products. is a major part of]","[a merger between Luxottica and Essilor, the UK's leading optician manufacturer of lenses and lenses.]",[and the other issuing a in the UK and will now make it into a retail brand dominated by electronics.],[. as the second largest manufacturer of glasses. is unlikely. is for a but there must be a risk],max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 56.65669631958008\nbeam: 113.73026275634766\ntop k: 177.36398315429688\ntop p: 203.10452270507812,"Since their impending merger was announced in January, there has been remarkably little comment about the huge proposed deal to combine Essilor and Luxottica."
6,"Media playback is not supported on this device\nThe Olympic silver medallist accused the organisation of ""ageism"" and having ""zero regard"" for her welfare.\nShe is the latest high-profile cyclist ...","[has apologised for the ""horrible"" behaviour of the British Cycling team.]","[has apologised to British Cycling's new chair Jonathan Browning. ""It's a really difficult question because you]","[that sport is ""cut-throat"" and a ""worst of luck"": she's been criticised by]",[to work with British Cycling. and her teammates being is now making a strong recovery at the World Class. Hasley],max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 27.57013511657715\nbeam: 98.8603286743164\ntop k: 64.00656127929688\ntop p: 387.70330810546875,"A ""medal at any cost"" approach created a ""culture of fear"" at British Cycling, says former rider Wendy Houvenaghel."
7,It's no joke. But Kareem Badr says people did laugh in 2009 when he and two friends paid $20000 (Â£13000) for the Hideout in Austin when it wasn't making money and the previous owner decided not t...,"[,,,,,,s are becoming more popular in the US. is a new metric]","[a comedy club in the United States. comedian Steve Byrne, a comedian with a career in comedy, says]","[in USA, which they don’t have on their own for decades. The Hollywood star is still in a hurry to take some]","[, a major era in American comedy, and a rise in traditional Hollywood comedy has largely resulted in a boom]",max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 147.81692504882812\nbeam: 56.5164680480957\ntop k: 107.35860443115234\ntop p: 76.3049087524414,Have you heard the one about the computer programmer who bought a failing comedy club in Texas and turned it into a million dollar a year business?
8,Relieved that the giant telecoms company would not be broken up they piled into the shares sending them up 3% in early trading.\nBT dodged a bullet - and as the chief executive of Ofcom Sharon Whi...,[of BT's pension scheme. of BT's pension scheme. of BT's pension scheme. of],"[of BT's giant pension scheme, Openreach, is a company that has fought in the courts to preserve and win]","[by shareholders who would support the ""golden share"" of Openreach would be on the rise in the next 12 months - as]",[BT to break the pensions from BT's existing private company Openreach.],max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 14.837325096130371\nbeam: 119.41099548339844\ntop k: 95.8749771118164\ntop p: 552.5446166992188,"The reaction from BT's investors told us much about media regulator Ofcom's ruling on the fate of Openreach, the BT subsidiary that provides much of the UK's broadband infrastructure."
9,"""I'm really looking forward to it - the home of Scottish football"" said Rodgers ahead of his maiden visit.\n""I hear the pitch is good a nice big pitch suits the speed in our team and our intensity...",[has been a key player in the Scottish Cup and has been a key player in the club's history.],"[- the home of Scottish football. ""We'll be prepared and focused. We know it's going to be a tough]","[has said he has had a ""difficult first win in the season in the Scottish football"" since returning to the club]","[to get the FA Cup on Sunday, after seeing England lose their first league Cup defeat to Celtic on Sunday.]",max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 14.055248260498047\nbeam: 32.43894958496094\ntop k: 47.841854095458984\ntop p: 71.72193145751953,Manager Brendan Rodgers is sure Celtic can exploit the wide open spaces of Hampden when they meet Rangers in Sunday's League Cup semi-final.
10,The move is in response to an £8m cut in the subsidy received from the Department of Employment and Learning (DEL).\nThe cut in undergraduate places will come into effect from September 2015.\nJob...,[is a major concern for the University of Northern Ireland.],"[in Northern Ireland's universities. ""The loss of any place is damaging to our economy,"" said Queen's vice-chancellor]",[and that's why UHE has been cutting dozens of universities in Belfast.],"[at the University of Belfast, Queen's has been left in the labour market since its recruitment as well as its uk and regional institutions]",max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 42.76444625854492\nbeam: 43.462833404541016\ntop k: 175.53285217285156\ntop p: 146.23580932617188,Queen's University Belfast is cutting 236 jobs and 290 student places due to a funding reduction.
11,The leaflets said the patient had been referred for an urgent appointment as their symptoms might indicate cancer.\nEast Sussex NHS Trust has put the mix-up down to an external company that distri...,"[was inserted with a 'two-week' information leaflet with an appointment letter. ""As soon as the error became]","[was inserted with an appointment letter. ""We apologise for any unnecessary anxiety this error may have caused.""]","[was withdrawn and hospital staff said they believed he would feel an immediate treatment. ""We are in forwarded our letter of apology.]",[that incorrect patient information leaflets were added to hospital appointments letters sent out in March.],max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 131.22964477539062\nbeam: 97.52108001708984\ntop k: 178.66380310058594\ntop p: 338.8961181640625,Hospital bosses in Sussex have apologised after about 850 patients were sent leaflets in error suggesting they might have cancer.
12,"Emily Thornberry said Labour would not ""frustrate Brexit"" even if it failed to amend the bill.\nTen shadow ministers were among 47 Labour MPs who rejected party orders to back it last week.\nShado...",[Labour's Labour leader has said he will vote against the Brexit bill unless it fails to amend it.],"[Jeremy Corbyn has said he will not ""frustrate"" Brexit even if it failed to amend the Brexit bill.]",[Labour and Labour MPs were all on the same line for the referendum last week.],"[the Government, Labour MPs, and the Conservative Party should not ratify an agenda on whether to back the Brexit bill.]",max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 25.30803108215332\nbeam: 22.335308074951172\ntop k: 38.537254333496094\ntop p: 57.17072677612305,The shadow foreign secretary has suggested Labour will continue to support legislation paving the way for Brexit as it passes through Parliament.
13,The National League sold the Republic of Ireland midfielder to the Cherries for £175000 in 2012 and had a 15% sell-on clause included in the deal.\nO'Kane moved for an undisclosed fee but Nicholso...,[has been sold to the Cherries for £175000 in 2012 and had a 15% sell-on clause included in the deal.],"[has been sold to the Cherries for an undisclosed fee. ""I don't think I'll be getting anything,""]","[. Ney Nicholson told Radio Devon Radio. ""I don't think I'll be getting anything"" - A]",[are still looking for new owners and managers following their move from Leeds to Oxford.],max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 40.46342468261719\nbeam: 24.520029067993164\ntop k: 186.7928009033203\ntop p: 64.08403778076172,Torquay United boss Kevin Nicholson says none of the money from Eunan O'Kane's move to Leeds from Bournemouth will go to the playing squad.
14,Iwan Wyn Lewis of Penygroes Gwynedd had been sectioned at Ysbyty Gwynedd after allegedly assaulting his mother.\nThe 36-year-old was visited by an officer in April 2016 about his bail arrangements...,[was found dead in the Menai Strait on 2 May.],"[Lewis was found dead in the Menai Strait on 2 May. A psychiatrist has said he was ""extremely unhappy""]","[, a condition he had reported, to the hospital, and has been placed in a hospital for six weeks.]","[s, Penygroes Gwynedd's Iwan Wyn Lewis had been beaten in police for several hours]",max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 102.64530944824219\nbeam: 52.499481201171875\ntop k: 28.421152114868164\ntop p: 646.8855590820312,North Wales Police has been criticised at an inquest for sending an officer to speak to a hospital patient with paranoid schizophrenia.
15,The 33-year-old has featured only twice for the Foxes this term having signed a new one-year deal with the Premier League newcomers in the summer.\nFormer Blackpool forward Taylor-Fletcher scored ...,[Taylor-Fletcher has signed a new one-year deal with the Foxes this term.],[Taylor-Fletcher has signed a new one-year deal with the Foxes.],[-born Chester Taylor-Fletcher has signed a new contract with the Foxes after impressing at Cambridge this season.],[Foxes star Taylor-Fletcher joined Blackpool after one year deal with The Buckets.],max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 18.801902770996094\nbeam: 17.094907760620117\ntop k: 35.44700241088867\ntop p: 292.4845886230469,Leicester City striker Gary Taylor-Fletcher has joined Sheffield Wednesday on an initial month-long loan.
16,"Dr Waleed Abdalati told the BBC the that continued access to data is in ""everyone's best interest"".\nMany US scientists are rushing to copy information onto servers outside the control of the fede...",[and the Trump administration has a broader view of climate change. to and and and Trump has backed],[that the Trump administration has pushed for a change in climate change policy.],"[. How to take the climate change risk off a certain scale? And as the Trump administration is gaining some funding, and some are]","[and that the Trump administration is being pushed to a clearer end if the EPA does not act, scientists have said.]",max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 91.95307159423828\nbeam: 31.117233276367188\ntop k: 109.0687026977539\ntop p: 61.381168365478516,"Limiting access to federal research would do an ""enormous disservice"" to the US and the world according to former Nasa chief scientist."
17,"The ska group tweeted the news: ""It is with deep regret that we say goodbye to our great friend the world's greatest drummer our beloved Brad. RIP.""\nBradbury joined The Specials in 1979 and conti...","[and that we have to say goodbye to our dear friend the world's greatest drummer Bradbury. RIP."" Bradbury was born]","[that Bradbury has passed away. ""It is with deepest regret that we say goodbye to our great friend the world's greatest]","[, Bradbury's family has said he was remembered as ""The Special AKA"" and has died on Monday .]",[& Family in The Splendid have been honoured by the band to reassemble and revive his husband Bradbury.],max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 68.43653869628906\nbeam: 32.57966613769531\ntop k: 110.12276458740234\ntop p: 222.39300537109375,"John ""Brad"" Bradbury, drummer with The Specials, has died at the age of 62."
18,The 14-time major champion playing in his first full PGA Tour event for almost 18 months carded a level-par second round of 72 but missed the cut by four shots after his first-round 76.\nWorld num...,[and....... in the US Open.. in the US Open],[. He missed the cut by four shots after his first-round 76 at Torrey Pines in San Diego.],"[Chris Woods by 87, after 71. PGA Tour champion James Woods missed an un-shot double round of]",[The US Open champion Joe Rose despite an impressive double-double in England after finishing on four over....],max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 202.69168090820312\nbeam: 52.87063217163086\ntop k: 301.1341247558594\ntop p: 323.0346374511719,"Tiger Woods missed the cut at the Farmers Insurance Open, as England's Justin Rose maintained a one-shot lead."
19,"Media playback is not supported on this device\n""If I push it I could go backwards or end up back on medication"" he said. ""There is also a chance of rejection.""\nThe former Manchester United Newca...",[has been unable to play in the Champions League since his kidney failure.],"[is not supported on this device. ""It is not like getting a football injury when you go to the gym and work a]","[to be able to return back to the US, Cole says. ""We can't get here as the game is really tough.]",[could see a club go up with something that could get a bit less in the Champions League.],max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 47.68309020996094\nbeam: 38.64506912231445\ntop k: 47.173912048339844\ntop p: 81.69593048095703,"Former England striker Andy Cole says he faces a ""long road ahead"" as he recovers from his recent kidney transplant."
20,Pakistan's telecoms regulator said the ban was no longer necessary because Google which owns YouTube had now launched a Pakistan-specific version.\nYouTube has denied claims that the authorities c...,[has announced that Google has banned YouTube from using YouTube.],[has imposed a ban on YouTube on Pakistan's YouTube.],[had been targeted by Pakistan for its logging and videos on YouTube.],[Government has decided that Google will end YouTube's licence ban over videos in Pakistan after a report by Indian authorities confirms they are ],max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 103.08558654785156\nbeam: 119.02886199951172\ntop k: 216.65989685058594\ntop p: 159.5364990234375,"Pakistan has unblocked the video sharing site, YouTube, more than three years after it was banned for posting a video deemed insulting to Islam."
21,"The 26-year-old was injured in last week's win over Exeter.\nDirector of rugby Richard Cockerill told BBC Radio Leicester: ""With eight weeks of the season to go that is probably the last we will s...",['s has signed a new contract with Leicester City.'s James Benjamin has been plagued by injuries since joining Worcester in],[man Benjamin Benjamin has signed a new contract but the length of the contract has not been revealed.],[has signed a new contract but the length of an contract hasn't been revealed.],[to be back at the University. Benjamin has yet to be able to return from injury from the injuries sustained in Exeter.],max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 119.0576400756836\nbeam: 42.24159240722656\ntop k: 46.81300735473633\ntop p: 70.0994644165039,"Leicester Tigers winger Miles Benjamin is likely to be out for the rest of the season because of a knee injury, reports BBC Radio Leicester."

In [14]:
import evaluate
rouge = evaluate.load("rouge")
greedy_rouge = []
beam_rouge = []
top_k_rouge = []
top_p_rouge = []

for i in range(50):
  greedy_rouge.append(rouge.compute(predictions=[results["greedy"][i][0]], references=[results["references"][i]]))
  beam_rouge.append(rouge.compute(predictions=[results["beam"][i][0]], references=[results["references"][i]]))
  top_k_rouge.append(rouge.compute(predictions=[results["top k"][i][0]], references=[results["references"][i]]))
  top_p_rouge.append(rouge.compute(predictions=[results["top p"][i][0]], references=[results["references"][i]]))

results["greedy rouge"] = greedy_rouge
results["beam rouge"] = beam_rouge
results["top k rouge"] = top_k_rouge
results["top p rouge"] = top_p_rouge
display(results)

Downloading builder script:   0%|          | 0.00/6.27k [00:00<?, ?B/s]

,prompt,greedy,beam,top k,top p,parameters,perplexity,references,greedy rouge,beam rouge,top k rouge,top p rouge
0,Prison Link Cymru had 1099 referrals in 2015-16 and said some ex-offenders were living rough for up to a year before finding suitable accommodation.\nWorkers at the charity claim investment in hou...,"[in Wales, a charity that has urged people to stay in a secure housing estate has said it is ""chronic"" for]","[in Wales, the Welsh Government has urged people to stay in a secure housing estate.]",[for the next five years and will run into it. who have been targeted by prison force members in Wales has been put in this post],"[to live in a secure apartment in Wales. It's a new, exciting and innovative development to use in housing in South Wales]",max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 46.846336364746094\nbeam: 33.5189094543457\ntop k: 148.06150817871094\ntop p: 58.72018051147461,"There is a ""chronic"" need for more housing for prison leavers in Wales, according to a charity.","{'rouge1': 0.5263157894736842, 'rouge2': 0.11111111111111112, 'rougeL': 0.21052631578947367, 'rougeLsum': 0.21052631578947367}","{'rouge1': 0.3125, 'rouge2': 0.06666666666666667, 'rougeL': 0.25, 'rougeLsum': 0.25}","{'rouge1': 0.186046511627907, 'rouge2': 0.048780487804878044, 'rougeL': 0.186046511627907, 'rougeLsum': 0.186046511627907}","{'rouge1': 0.3, 'rouge2': 0.052631578947368425, 'rougeL': 0.19999999999999998, 'rougeLsum': 0.19999999999999998}"
1,Officers searched properties in the Waterfront Park and Colonsay View areas of the city on Wednesday.\nDetectives said three firearms ammunition and a five-figure sum of money were recovered.\nA 2...,[Police have recovered three firearms ammunition and a five-figure sum of money.],[Police have recovered three firearms ammunition and a five-figure sum of money.],"[are in custody and have arrested 26-year-old Amarsh Scott, whose family has been forced to return the missing person]",[Police Officers have recovered three firearms ammunition and five-figure sums of money.],max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 41.20834732055664\nbeam: 41.20834732055664\ntop k: 68.57975006103516\ntop p: 87.23341369628906,"A man has appeared in court after firearms, ammunition and cash were seized by police in Edinburgh.","{'rouge1': 0.33333333333333337, 'rouge2': 0.14285714285714288, 'rougeL': 0.20000000000000004, 'rougeLsum': 0.20000000000000004}","{'rouge1': 0.33333333333333337, 'rouge2': 0.14285714285714288, 'rougeL': 0.20000000000000004, 'rougeLsum': 0.20000000000000004}","{'rouge1': 0.15789473684210528, 'rouge2': 0.0, 'rougeL': 0.10526315789473684, 'rougeLsum': 0.10526315789473684}","{'rouge1': 0.26666666666666666, 'rouge2': 0.14285714285714288, 'rougeL': 0.20000000000000004, 'rougeLsum': 0.20000000000000004}"
2,Jordan Hill Brittany Covington and Tesfaye Cooper all 18 and Tanishia Covington 24 appeared in a Chicago court on Friday.\nThe four have been charged with hate crimes and aggravated kidnapping and...,"[and,, and have been charged with hate crimes and aggravated kidnapping. and have been]","[who have been charged with hate crimes, aggravated kidnapping and battery among other things.]",[All-American. have been charged with hate crimes and aggravated kidnapping as three assailants are found],"[An Alabama woman who has been sentenced to 21 years in prison is awaiting trial for assaulting his mother, Tim Hill, in ]",max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 60.31381607055664\nbeam: 46.98090362548828\ntop k: 133.20643615722656\ntop p: 39.66783142089844,"Four people accused of kidnapping and torturing a mentally disabled man in a ""racially motivated"" attack streamed on Facebook have been denied bail.","{'rouge1': 0.2162162162162162, 'rouge2': 0.1142857142857143, 'rougeL': 0.2162162162162162, 'rougeLsum': 0.2162162162162162}","{'rouge1': 0.2162162162162162, 'rouge2': 0.1142857142857143, 'rougeL': 0.1081081081081081, 'rougeLsum': 0.1081081081081081}","{'rouge1': 0.20512820512820512, 'rouge2': 0.05405405405405406, 'rougeL': 0.10256410256410256, 'rougeLsum': 0.10256410256410256}","{'rouge1': 0.08888888888888888, 'rouge2': 0.0, 'rougeL': 0.04444444444444444, 'rougeLsum': 0.04444444444444444}"
3,The 48-year-old former Arsenal goalkeeper played for the Royals for four years.\nHe was appointed youth academy director in 2000 and has been director of football since 2003.\nA West Brom statemen...,[keeper David West Brom has been appointed a youth academy director of football since 2003.],['s former Arsenal goalkeeper has played for the Royals for four years and has been director of football since 2003.],[goalkeeper David Eldrado spent eight months working in the Athletic Union Division.],[Arsenal goalkeeper Ibrahim Ibrahimovic has been appointed manager of the University of Newcastle United.],max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 209.69117736816406\nbeam: 33.44632339477539\ntop k: 398.7690124511719\ntop p: 36.21345901489258,"West Brom have appointed Nicky Hammond as technical director, ending his 20-year association with Reading.","{'rouge1': 0.2580645161290323, 'rouge2': 0.0689655172413793, 'rougeL': 0.2580645161290323, 'rougeLsum': 0.2580645161290323}","{'rouge1': 0.05555555555555556, 'rouge2': 0.0, 'rougeL': 0.05555555555555556, 'rougeLsum': 0.05555555555555556}","{'rouge1': 0.0, 'rouge2': 0.0, 'rougeL': 0.0, 'rougeLsum': 0.0}","{'rouge1': 0.06666666666666667, 'rouge2': 0.0, 'rougeL': 0.06666666666666667, 'rougeLsum': 0.06666666666666667}"
4,Restoring the function of the organ - which helps control blood sugar levels - reversed symptoms of diabetes in animal experiments.\nThe study published in the journal Cell says the diet reboots t...,"[and. ""The results of the study have been very exciting,"" said Dr James Longo. ""The results of the study have been]","[. ""I was glad to have something to eat"" in a diet that regenerated a cell in the pancrea]","[- in humans - that can be described as ""possibly quite exciting from the end of the day"" in animal experiment results]","[, however, a body is reset to form a new system. In many studies it has a potential to retrain glucose]",max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 20.34456443786621\nbeam: 99.07830810546875\ntop k: 135.201904296875\ntop p: 144.0154571533203,"The pancreas can be triggered to regenerate itself through a type of fasting diet, say US researchers.","{'rouge1': 0.10526315789473684, 'rouge2': 0.0, 'rougeL': 0.10526315789473684, 'rougeLsum': 0.10526315789473684}","{'rouge1': 0.22857142857142856, 'rouge2': 0.0, 'rougeL': 0.17142857142857143, 'rougeLsum': 0.17142857142857143}","{'rouge1': 0.2162162162162162, 'rouge2': 0.05714285714285714, 'rougeL': 0.16216216216216214, 'rougeLsum': 0.16216216216216214}","{'rouge1': 0.1081081081081081, 'rouge2': 0.0, 'rougeL': 0.1081081081081081, 'rougeLsum': 0.1081081081081081}"
5,But there certainly should be.\nThese are two of the biggest firms in the lucrative international business of making spectacles. France's Essilor is the world's number one manufacturer of lenses a...,"[and of optical optical products. and, and and of optical optical products. is a major part of]","[a merger between Luxottica and Essilor, the UK's leading optician manufacturer of lenses and lenses.]",[and the other issuing a in the UK and will now make it into a retail brand dominated by electronics.],[. as the second largest manufacturer of glasses. is unlikely. is for a but there must be a risk],max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 56.65669631958008\nbeam: 113.73026275634766\ntop k: 177.36398315429688\ntop p: 203.10452270507812,"Since their impending merger was announced in January, there has been remarkably little comment about the huge proposed deal to combine Essilor and Luxottica.","{'rouge1': 0.048780487804878044, 'rouge2': 0.0, 'rougeL': 0.048780487804878044, 'rougeLsum': 0.048780487804878044}","{'rouge1': 0.25, 'rouge2': 0.0, 'rougeL': 0.15, 'rougeLsum': 0.15}","{'rouge1': 0.13636363636363635, 'rouge2': 0.0, 'rougeL': 0.13636363636363635, 'rougeLsum': 0.13636363636363635}","{'rouge1': 0.09523809523809525, 'rouge2': 0.0, 'rougeL': 0.04761904761904762, 'rougeLsum': 0.04761904761904762}"
6,"Media playback is not supported on this device\nThe Olympic silver medallist accused the organisation of ""ageism"" and having ""zero regard"" for her welfare.\nShe is the latest high-profile cyclist ...","[has apologised for the ""horrible"" behaviour of the British Cycling team.]","[has apologised to British Cycling's new chair Jonathan Browning. ""It's a really difficult question because you]","[that sport is ""cut-throat"" and a ""worst of luck"": she's been criticised by]",[to work with British Cycling. and her teammates being is now making a strong recovery at the World Class. Hasley],max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 27.57013511657715\nbeam: 98.8603286743164\ntop k: 64.00656127929688\ntop p: 387.70330810546875,"A ""medal at any cost"" approach created a ""culture of fear"" at British Cycling, says former rider Wendy Houvenaghel.","{'rouge1': 0.19999999999999998, 'rouge2': 0.07142857142857142, 'rougeL': 0.19999999999999998, 'rougeLsum': 0.19999999999999998}","{'rouge1': 0.16216216216216214, 'rouge2': 0.05714285714285714, 'rougeL': 0.10810810810810811, 'rougeLsum': 0.10810810810810811}","{'rouge1': 0.11764705882352941, 'rouge2': 0.0, 'rougeL': 0.11764705882352941, 'rougeLsum': 0.11764705882352941}","{'rouge1': 0.20512820512820512, 'rouge2': 0.05405405405405406, 'rougeL': 0.10256410256410256, 'rougeLsum': 0.10256410256410256}"
7,It's no joke. But Kareem Badr says people did laugh in 2009 when he and two friends paid $20000 (Â£13000) for the Hideout in Austin when it wasn't making money and the previous owner decided not t...,"[,,,,,,s are becoming more popular in the US. is a new metric]","[a comedy club in the United States. comedian Steve Byrne, a comedian with a career in comedy, says]","[in USA, which they don’t have on their own for decades. The Hollywood star is still in a hurry to take some]","[, a major era in American comedy, and a rise in traditional Hollywood comedy has largely resulted in a boom]",max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 147.81692504882812\nbeam: 56.5164680480957\ntop k: 107.35860443115234\ntop p: 76.3049087524414,Have you heard the one about the computer programmer who bought a failing comedy club in Texas and turned it into a million dollar a year business?,"{'rouge1': 0.15384615384615383, 'rouge2': 0.0, 'rougeL': 0.10256410256410256, 'rougeLsum': 0.10256410256410256}","{'rouge1': 0.3111111111111111, 'rouge2': 0.0930232558139535, 'rougeL': 0.26666666666666666, 'rougeLsum': 0.26666666666666666}","{'rouge1': 0.15999999999999998, 'rouge2': 0.0, 'rougeL': 0.15999999999999998, 'rougeLsum': 0.15999999999999998}","{'rouge1': 0.2608695652173913, 'rouge2': 0.0, 'rougeL': 0.21739130434782608, 'rougeLsum': 0.21739130434782608}"
8,Relieved that the giant telecoms company would not be broken up they piled into the shares sending them up 3% in early trading.\nBT dodged a bullet - and as the chief executive of Ofcom Sharon Whi...,[of BT's pension scheme. of BT's pension scheme. of BT's pension scheme. of],"[of BT's giant pension scheme, Openreach, is a company that has fought in the courts to preserve and win]","[by shareholders who would support the ""golden share"" of Openreach would be on the rise in the next 12 months - as]",[BT to break the pensions from BT's existing private company Openreach.],max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 14.837325096130371\nbeam: 119.41099548339844\ntop k: 95.8749771118164\ntop p: 552.5446166992188,"The reaction from BT's investors told us much about media regulator Ofcom's ruling on the fate of Openreach, the BT subsidiary that provides much of the UK's broadband infrastructure.","{'rouge1': 0.2916666666666667, 'rouge2': 0.043478260869565216, 'rougeL': 0.25, 'rougeLsum': 0.25}","{'rouge1': 0.23076923076923075, 'rouge2': 0.039999999999999994, 'rougeL': 0.19230769230769232, 'rougeLsum': 0.19230769230769232}","{'rouge1': 0.22641509433962265, 'rouge2': 0.0784313725490196, 'rougeL': 0.18867924528301888, 'rougeLsum': 0.18867924528301888}","{'rouge1': 0.2727272727272727, 'rouge2': 0.09523809523809523, 'rougeL': 0.22727272727272727, 'rougeLsum': 0.22727272727272727}"
9,"""I'm really looking forward to it - the home of Scottish football"" said Rodgers ahead of his maiden visit.\n""I hear the pitch is good a nice big pitch suits the speed in our team and our intensity...",[has been a key player in the Scottish Cup and has been a key player in the club's history.],"[- the home of Scottish football. ""We'll be prepared and focused. We know it's going to be a tough]","[has said he has had a ""difficult first win in the season in the Scottish football"" since returning to the club]","[to get the FA Cup on Sunday, after seeing England lose their first league Cup defeat to Celtic on Sunday.]",max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 14.055248260498047\nbeam: 32.43894958496094\ntop k: 47.841854095458984\ntop p: 71.72193145751953,Manager Brendan Rodgers is sure Celtic can exploit the wide open spaces of Hampden when they meet Rangers in Sunday's League Cup semi-final.,"{'rouge1': 0.17777777777777778, 'rouge2': 0.0, 'rougeL': 0.1333333333333333, 'rougeLsum': 0.1333333333333333}","{'rouge1': 0.1333333333333333, 'rouge2': 0.0, 'rougeL': 0.1333333333333333, 'rougeLsum': 0.1333333333333333}","{'rouge1': 0.08695652173913043, 'rouge2': 0.0, 'rougeL': 0.08695652173913043, 'rougeLsum': 0.08695652173913043}","{'rouge1': 0.22222222222222224, 'rouge2': 0.04651162790697675, 'rougeL': 0.17777777777777778, 'rougeLsum': 0.17777777777777778}"
10,The move is in response to an £8m cut in the subsidy received from the Department of Employment and Learning (DEL).\nThe cut in undergraduate places will come into effect from September 2015.\nJob...,[is a major concern for the University of Northern Ireland.],"[in Northern Ireland's universities. ""The loss of any place is damaging to our economy,"" said Queen's vice-chancellor]",[and that's why UHE has been cutting dozens of universities in Belfast.],"[at the University of Belfast, Queen's has been left in the labour market since its recruitment as well as its uk and regional institutions]",max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 42.76444625854492\nbeam: 43.462833404541016\ntop k: 175.53285217285156\ntop p: 146.23580932617188,Queen's University Belfast is cutting 236 jobs and 290 student places due to a funding reduction.,"{'rouge1': 0.22222222222222224, 'rouge2': 0.0, 'rougeL': 0.14814814814814817, 'rougeLsum': 0.14814814814814817}","{'rouge1': 0.2162162162162162, 'rouge2': 0.05714285714285714, 'rougeL': 0.16216216216216214, 'rougeLsum': 0.16216216216216214}","{'rouge1': 0.26666666666666666, 'rouge2': 0.0, 'rougeL': 0.13333333333333333, 'rougeLsum': 0.13333333333333333}","{'rouge1': 0.2380952380952381, 'rouge2': 0.05, 'rougeL': 0.14285714285714282, 'rougeLsum': 0.14285714285714282}"
11,The leaflets said the patient had been referred for an urgent appointment as their symptoms might indicate cancer.\nEast Sussex NHS Trust has put the mix-up down to an external company that distri...,"[was inserted with a 'two-week' information leaflet with an appointment letter. ""As soon as the error became]","[was inserted with an appointment letter. ""We apologise for any unnecessary anxiety this error may have caused.""]","[was withdrawn and hospital staff said they believed he would feel an immediate treatment. ""We are in forwarded our letter of apology.]",[that incorrect patient information leaflets were added to hospital appointments letters sent out in March.],max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 131.22964477539062\nbeam: 97.52108001708984\ntop k: 178.66380310058594\ntop p: 338.8961181640625,Hospital bosses in Sussex have apologised after about 850 patients were sent leaflets in error suggesting they might have cancer.,"{'rouge1': 0.052631578947368425, 'rouge2': 0.0, 'rougeL': 0.052631578947368425, 'rougeLsum': 0.052631578947368425}","{'rouge1': 0.1081081081081081, 'rouge2': 0.0, 'rougeL': 0.1081081081081081, 'rougeLsum': 0.1081081081081081}","{'rouge1': 0.14285714285714282, 'rouge2': 0.0, 'rougeL': 0.09523809523809525, 'rougeLsum': 0.09523809523809525}","{'rouge1': 0.28571428571428575, 'rouge2': 0.0, 'rougeL': 0.17142857142857143, 'rougeLsum': 0.17142857142857143}"
12,"Emily Thornberry said Labour would not ""frustrate Brexit"" even if it failed to amend the bill.\nTen shadow ministers were among 47 Labour MPs who rejected party orders to back it last week.\nShado...",[Labour's Labour leader has said he will vote against the Brexit bill unless it fails to amend it.],"[Jeremy Corbyn has said he will not ""frustrate"" Brexit even if it failed to amend the Brexit bill.]",[Labour and Labour MPs were all on the same line for the referendum last week.],"[the Government, Labour MPs, and the Conservative Party should not ratify an agenda on whether to back the Brexit bill.]",max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 25.30803108215332\nbeam: 22.335308074951172\ntop k: 38.537254333496094\ntop p: 57.17072677612305,The shadow foreign secretary has suggested Labour will continue to support legislation paving the way for Brexit as it passes through Parliament.,"{'rouge1': 0.3414634146341463, 'rouge2': 0.0, 'rougeL': 0.24390243902439024, 'rougeLsum': 0.24390243902439024}","{'rouge1': 0.3, 'rouge2': 0.0, 'rougeL': 0.25, 'rougeLsum': 0.25}","{'rouge1': 0.21621621621621623, 'rouge2': 0.0, 'rougeL': 0.16216216216216214, 'rougeLsum': 0.16216216216216214}","{'rouge1': 0.23809523809523808, 'rouge2': 0.0, 'rougeL': 0.23809523809523808, 'rougeLsum': 0.23809523809523808}"
13,The National League sold the Republic of Ireland midfielder to the Cherries for £175000 in 2012 and had a 15% sell-on clause included in the deal.\nO'Kane moved for an undisclosed fee but Nicholso...,[has been sold to the Cherries for £175000 in 2012 and had a 15% sell-on clause included in the deal.],"[has been sold to the Cherries for an undisclosed fee. ""I don't think I'll be getting anything,""]","[. Ney Nicholson told Radio Devon Radio. ""I don't think I'll be getting anything"" - A]",[are still looking for new owners and managers following their move from Leeds to Oxford.],max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 40.46342468261719\nbeam: 24.520029067993164\ntop k: 186.7928009033203\ntop p: 64.08403778076172,Torquay United boss Kevin Nicholson says none of the money from Eunan O'Kane's move to Leeds from Bournemouth will go to the playing squad.,"{'rouge1': 0.12765957446808512, 'rouge2': 0.044444444444444446, 'rougeL': 0.0851063829787234, 'rougeLsum': 0.0851063829787234}","{'rouge1': 0.08888888888888889, 'rouge2': 0.046511627906976744, 'rougeL': 0.08888888888888889, 'rougeLsum': 0.08888888888888889}","{'rouge1': 0.04761904761904762, 'rouge2': 0.0, 'rougeL': 0.04761904761904762, 'rougeLsum': 0.04761904761904762}","{'rouge1': 0.1951219512195122, 'rouge2': 0.0, 'rougeL': 0.14634146341463417, 'rougeLsum': 0.14634146341463417}"

In [16]:
import evaluate
bertscore = evaluate.load("bertscore")
greedy_bertscore = []
beam_bertscore = []
top_k_bertscore = []
top_p_bertscore = []

for i in range(50):
  greedy_bertscore.append(bertscore.compute(predictions=[results["greedy"][i][0]], references=[results["references"][i]], lang = 'en'))
  beam_bertscore.append(bertscore.compute(predictions=[results["beam"][i][0]], references=[results["references"][i]], lang = 'en'))
  top_k_bertscore.append(bertscore.compute(predictions=[results["top k"][i][0]], references=[results["references"][i]], lang = 'en'))
  top_p_bertscore.append(bertscore.compute(predictions=[results["top p"][i][0]], references=[results["references"][i]], lang = 'en'))

results["greedy bert"] = greedy_bertscore
results["beam bert"] = beam_bertscore
results["top k bert"] = top_k_bertscore
results["top p bert"] = top_p_bertscore
display(results)

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/482 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.42G [00:00<?, ?B/s]

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

,prompt,greedy,beam,top k,top p,parameters,perplexity,references,greedy rouge,beam rouge,top k rouge,top p rouge,greedy bert,beam bert,top k bert,top p bert
0,Prison Link Cymru had 1099 referrals in 2015-16 and said some ex-offenders were living rough for up to a year before finding suitable accommodation.\nWorkers at the charity claim investment in hou...,"[in Wales, a charity that has urged people to stay in a secure housing estate has said it is ""chronic"" for]","[in Wales, the Welsh Government has urged people to stay in a secure housing estate.]",[for the next five years and will run into it. who have been targeted by prison force members in Wales has been put in this post],"[to live in a secure apartment in Wales. It's a new, exciting and innovative development to use in housing in South Wales]",max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 46.846336364746094\nbeam: 33.5189094543457\ntop k: 148.06150817871094\ntop p: 58.72018051147461,"There is a ""chronic"" need for more housing for prison leavers in Wales, according to a charity.","{'rouge1': 0.5263157894736842, 'rouge2': 0.11111111111111112, 'rougeL': 0.21052631578947367, 'rougeLsum': 0.21052631578947367}","{'rouge1': 0.3125, 'rouge2': 0.06666666666666667, 'rougeL': 0.25, 'rougeLsum': 0.25}","{'rouge1': 0.186046511627907, 'rouge2': 0.048780487804878044, 'rougeL': 0.186046511627907, 'rougeLsum': 0.186046511627907}","{'rouge1': 0.3, 'rouge2': 0.052631578947368425, 'rougeL': 0.19999999999999998, 'rougeLsum': 0.19999999999999998}","{'precision': [0.8771550059318542], 'recall': [0.8916277289390564], 'f1': [0.8843321800231934], 'hashcode': 'roberta-large_L17_no-idf_version=0.3.12(hug_trans=4.50.0)'}","{'precision': [0.8947465419769287], 'recall': [0.8781324625015259], 'f1': [0.8863616585731506], 'hashcode': 'roberta-large_L17_no-idf_version=0.3.12(hug_trans=4.50.0)'}","{'precision': [0.8358310461044312], 'recall': [0.8665710687637329], 'f1': [0.8509235382080078], 'hashcode': 'roberta-large_L17_no-idf_version=0.3.12(hug_trans=4.50.0)'}","{'precision': [0.8721945285797119], 'recall': [0.8638125658035278], 'f1': [0.867983341217041], 'hashcode': 'roberta-large_L17_no-idf_version=0.3.12(hug_trans=4.50.0)'}"
1,Officers searched properties in the Waterfront Park and Colonsay View areas of the city on Wednesday.\nDetectives said three firearms ammunition and a five-figure sum of money were recovered.\nA 2...,[Police have recovered three firearms ammunition and a five-figure sum of money.],[Police have recovered three firearms ammunition and a five-figure sum of money.],"[are in custody and have arrested 26-year-old Amarsh Scott, whose family has been forced to return the missing person]",[Police Officers have recovered three firearms ammunition and five-figure sums of money.],max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 41.20834732055664\nbeam: 41.20834732055664\ntop k: 68.57975006103516\ntop p: 87.23341369628906,"A man has appeared in court after firearms, ammunition and cash were seized by police in Edinburgh.","{'rouge1': 0.33333333333333337, 'rouge2': 0.14285714285714288, 'rougeL': 0.20000000000000004, 'rougeLsum': 0.20000000000000004}","{'rouge1': 0.33333333333333337, 'rouge2': 0.14285714285714288, 'rougeL': 0.20000000000000004, 'rougeLsum': 0.20000000000000004}","{'rouge1': 0.15789473684210528, 'rouge2': 0.0, 'rougeL': 0.10526315789473684, 'rougeLsum': 0.10526315789473684}","{'rouge1': 0.26666666666666666, 'rouge2': 0.14285714285714288, 'rougeL': 0.20000000000000004, 'rougeLsum': 0.20000000000000004}","{'precision': [0.8914594650268555], 'recall': [0.8753349781036377], 'f1': [0.8833236694335938], 'hashcode': 'roberta-large_L17_no-idf_version=0.3.12(hug_trans=4.50.0)'}","{'precision': [0.8914594650268555], 'recall': [0.8753349781036377], 'f1': [0.8833236694335938], 'hashcode': 'roberta-large_L17_no-idf_version=0.3.12(hug_trans=4.50.0)'}","{'precision': [0.8504212498664856], 'recall': [0.8522648811340332], 'f1': [0.8513420820236206], 'hashcode': 'roberta-large_L17_no-idf_version=0.3.12(hug_trans=4.50.0)'}","{'precision': [0.8912416696548462], 'recall': [0.8817635178565979], 'f1': [0.8864772319793701], 'hashcode': 'roberta-large_L17_no-idf_version=0.3.12(hug_trans=4.50.0)'}"
2,Jordan Hill Brittany Covington and Tesfaye Cooper all 18 and Tanishia Covington 24 appeared in a Chicago court on Friday.\nThe four have been charged with hate crimes and aggravated kidnapping and...,"[and,, and have been charged with hate crimes and aggravated kidnapping. and have been]","[who have been charged with hate crimes, aggravated kidnapping and battery among other things.]",[All-American. have been charged with hate crimes and aggravated kidnapping as three assailants are found],"[An Alabama woman who has been sentenced to 21 years in prison is awaiting trial for assaulting his mother, Tim Hill, in ]",max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 60.31381607055664\nbeam: 46.98090362548828\ntop k: 133.20643615722656\ntop p: 39.66783142089844,"Four people accused of kidnapping and torturing a mentally disabled man in a ""racially motivated"" attack streamed on Facebook have been denied bail.","{'rouge1': 0.2162162162162162, 'rouge2': 0.1142857142857143, 'rougeL': 0.2162162162162162, 'rougeLsum': 0.2162162162162162}","{'rouge1': 0.2162162162162162, 'rouge2': 0.1142857142857143, 'rougeL': 0.1081081081081081, 'rougeLsum': 0.1081081081081081}","{'rouge1': 0.20512820512820512, 'rouge2': 0.05405405405405406, 'rougeL': 0.10256410256410256, 'rougeLsum': 0.10256410256410256}","{'rouge1': 0.08888888888888888, 'rouge2': 0.0, 'rougeL': 0.04444444444444444, 'rougeLsum': 0.04444444444444444}","{'precision': [0.850257933139801], 'recall': [0.8477525115013123], 'f1': [0.8490034341812134], 'hashcode': 'roberta-large_L17_no-idf_version=0.3.12(hug_trans=4.50.0)'}","{'precision': [0.877109944820404], 'recall': [0.8551229238510132], 'f1': [0.8659769296646118], 'hashcode': 'roberta-large_L17_no-idf_version=0.3.12(hug_trans=4.50.0)'}","{'precision': [0.8673549294471741], 'recall': [0.8569558262825012], 'f1': [0.8621240258216858], 'hashcode': 'roberta-large_L17_no-idf_version=0.3.12(hug_trans=4.50.0)'}","{'precision': [0.8500154614448547], 'recall': [0.8524870276451111], 'f1': [0.8512494564056396], 'hashcode': 'roberta-large_L17_no-idf_version=0.3.12(hug_trans=4.50.0)'}"
3,The 48-year-old former Arsenal goalkeeper played for the Royals for four years.\nHe was appointed youth academy director in 2000 and has been director of football since 2003.\nA West Brom statemen...,[keeper David West Brom has been appointed a youth academy director of football since 2003.],['s former Arsenal goalkeeper has played for the Royals for four years and has been director of football since 2003.],[goalkeeper David Eldrado spent eight months working in the Athletic Union Division.],[Arsenal goalkeeper Ibrahim Ibrahimovic has been appointed manager of the University of Newcastle United.],max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 209.69117736816406\nbeam: 33.44632339477539\ntop k: 398.7690124511719\ntop p: 36.21345901489258,"West Brom have appointed Nicky Hammond as technical director, ending his 20-year association with Reading.","{'rouge1': 0.2580645161290323, 'rouge2': 0.0689655172413793, 'rougeL': 0.2580645161290323, 'rougeLsum': 0.2580645161290323}","{'rouge1': 0.05555555555555556, 'rouge2': 0.0, 'rougeL': 0.05555555555555556, 'rougeLsum': 0.05555555555555556}","{'rouge1': 0.0, 'rouge2': 0.0, 'rougeL': 0.0, 'rougeLsum': 0.0}","{'rouge1': 0.06666666666666667, 'rouge2': 0.0, 'rougeL': 0.06666666666666667, 'rougeLsum': 0.06666666666666667}","{'precision': [0.8712450265884399], 'recall': [0.8643907308578491], 'f1': [0.8678043484687805], 'hashcode': 'roberta-large_L17_no-idf_version=0.3.12(hug_trans=4.50.0)'}","{'precision': [0.8610790967941284], 'recall': [0.8653084635734558], 'f1': [0.863188624382019], 'hashcode': 'roberta-large_L17_no-idf_version=0.3.12(hug_trans=4.50.0)'}","{'precision': [0.8473503589630127], 'recall': [0.8479368686676025], 'f1': [0.8476434946060181], 'hashcode': 'roberta-large_L17_no-idf_version=0.3.12(hug_trans=4.50.0)'}","{'precision': [0.8666940331459045], 'recall': [0.8645501732826233], 'f1': [0.8656207919120789], 'hashcode': 'roberta-large_L17_no-idf_version=0.3.12(hug_trans=4.50.0)'}"
4,Restoring the function of the organ - which helps control blood sugar levels - reversed symptoms of diabetes in animal experiments.\nThe study published in the journal Cell says the diet reboots t...,"[and. ""The results of the study have been very exciting,"" said Dr James Longo. ""The results of the study have been]","[. ""I was glad to have something to eat"" in a diet that regenerated a cell in the pancrea]","[- in humans - that can be described as ""possibly quite exciting from the end of the day"" in animal experiment results]","[, however, a body is reset to form a new system. In many studies it has a potential to retrain glucose]",max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 20.34456443786621\nbeam: 99.07830810546875\ntop k: 135.201904296875\ntop p: 144.0154571533203,"The pancreas can be triggered to regenerate itself through a type of fasting diet, say US researchers.","{'rouge1': 0.10526315789473684, 'rouge2': 0.0, 'rougeL': 0.10526315789473684, 'rougeLsum': 0.10526315789473684}","{'rouge1': 0.22857142857142856, 'rouge2': 0.0, 'rougeL': 0.17142857142857143, 'rougeLsum': 0.17142857142857143}","{'rouge1': 0.2162162162162162, 'rouge2': 0.05714285714285714, 'rougeL': 0.16216216216216214, 'rougeLsum': 0.16216216216216214}","{'rouge1': 0.1081081081081081, 'rouge2': 0.0, 'rougeL': 0.1081081081081081, 'rougeLsum': 0.1081081081081081}","{'precision': [0.8375972509384155], 'recall': [0.8334270715713501], 'f1': [0.8355069756507874], 'hashcode': 'roberta-large_L17_no-idf_version=0.3.12(hug_trans=4.50.0)'}","{'precision': [0.8648090958595276], 'recall': [0.8681292533874512], 'f1': [0.8664660453796387], 'hashcode': 'roberta-large_L17_no-idf_version=0.3.12(hug_trans=4.50.0)'}","{'precision': [0.8379285931587219], 'recall': [0.8398618102073669], 'f1': [0.8388940691947937], 'hashcode': 'roberta-large_L17_no-idf_version=0.3.12(hug_trans=4.50.0)'}","{'precision': [0.8752287030220032], 'recall': [0.8678045272827148], 'f1': [0.8715008497238159], 'hashcode': 'roberta-large_L17_no-idf_version=0.3.12(hug_trans=4.50.0)'}"
5,But there certainly should be.\nThese are two of the biggest firms in the lucrative international business of making spectacles. France's Essilor is the world's number one manufacturer of lenses a...,"[and of optical optical products. and, and and of optical optical products. is a major part of]","[a merger between Luxottica and Essilor, the UK's leading optician manufacturer of lenses and lenses.]",[and the other issuing a in the UK and will now make it into a retail brand dominated by electronics.],[. as the second largest manufacturer of glasses. is unlikely. is for a but there must be a risk],max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 56.65669631958008\nbeam: 113.73026275634766\ntop k: 177.36398315429688\ntop p: 203.10452270507812,"Since their impending merger was announced in January, there has been remarkably little comment about the huge proposed deal to combine Essilor and Luxottica.","{'rouge1': 0.048780487804878044, 'rouge2': 0.0, 'rougeL': 0.048780487804878044, 'rougeLsum': 0.048780487804878044}","{'rouge1': 0.25, 'rouge2': 0.0, 'rougeL': 0.15, 'rougeLsum': 0.15}","{'rouge1': 0.13636363636363635, 'rouge2': 0.0, 'rougeL': 0.13636363636363635, 'rougeLsum': 0.13636363636363635}","{'rouge1': 0.09523809523809525, 'rouge2': 0.0, 'rougeL': 0.04761904761904762, 'rougeLsum': 0.04761904761904762}","{'precision': [0.8116430044174194], 'recall': [0.8209283947944641], 'f1': [0.8162592649459839], 'hashcode': 'roberta-large_L17_no-idf_version=0.3.12(hug_trans=4.50.0)'}","{'precision': [0.8768376111984253], 'recall': [0.8772794008255005], 'f1': [0.8770584464073181], 'hashcode': 'roberta-large_L17_no-idf_version=0.3.12(hug_trans=4.50.0)'}","{'precision': [0.8396511077880859], 'recall': [0.8396462202072144], 'f1': [0.8396486639976501], 'hashcode': 'roberta-large_L17_no-idf_version=0.3.12(hug_trans=4.50.0)'}","{'precision': [0.8378311395645142], 'recall': [0.8308576345443726], 'f1': [0.8343298435211182], 'hashcode': 'roberta-large_L17_no-idf_version=0.3.12(hug_trans=4.50.0)'}"
6,"Media playback is not supported on this device\nThe Olympic silver medallist accused the organisation of ""ageism"" and having ""zero regard"" for her welfare.\nShe is the latest high-profile cyclist ...","[has apologised for the ""horrible"" behaviour of the British Cycling team.]","[has apologised to British Cycling's new chair Jonathan Browning. ""It's a really difficult question because you]","[that sport is ""cut-throat"" and a ""worst of luck"": she's been criticised by]",[to work with British Cycling. and her teammates being is now making a strong recovery at the World Class. Hasley],max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 27.57013511657715\nbeam: 98.8603286743164\ntop k: 64.00656127929688\ntop p: 387.70330810546875,"A ""medal at any cost"" approach created a ""culture of fear"" at British Cycling, says former rider Wendy Houvenaghel.","{'rouge1': 0.19999999999999998, 'rouge2': 0.07142857142857142, 'rougeL': 0.19999999999999998, 'rougeLsum': 0.19999999999999998}","{'rouge1': 0.16216216216216214, 'rouge2': 0.05714285714285714, 'rougeL': 0.10810810810810811, 'rougeLsum': 0.10810810810810811}","{'rouge1': 0.11764705882352941, 'rouge2': 0.0, 'rougeL': 0.11764705882352941, 'rougeLsum': 0.11764705882352941}","{'rouge1': 0.20512820512820512, 'rouge2': 0.05405405405405406, 'rougeL': 0.10256410256410256, 'rougeLsum': 0.10256410256410256}","{'precision': [0.9078989028930664], 'recall': [0.8479021787643433], 'f1': [0.8768755197525024], 'hashcode': 'roberta-large_L17_no-idf_version=0.3.12(hug_trans=4.50.0)'}","{'precision': [0.8512740135192871], 'recall': [0.8343318700790405], 'f1': [0.8427177667617798], 'hashcode': 'roberta-large_L17_no-idf_version=0.3.12(hug_trans=4.50.0)'}","{'precision': [0.8650521039962769], 'recall': [0.8364968299865723], 'f1': [0.8505348563194275], 'hashcode': 'roberta-large_L17_no-idf_version=0.3.12(hug_trans=4.50.0)'}","{'precision': [0.8556290864944458], 'recall': [0.8285119533538818], 'f1': [0.8418521881103516], 'hashcode': 'roberta-large_L17_no-idf_version=0.3.12(hug_trans=4.50.0)'}"
7,It's no joke. But Kareem Badr says people did laugh in 2009 when he and two friends paid $20000 (Â£13000) for the Hideout in Austin when it wasn't making money and the previous owner decided not t...,"[,,,,,,s are becoming more popular in the US. is a new metric]","[a comedy club in the United States. comedian Steve Byrne, a comedian with a career in comedy, says]","[in USA, which they don’t have on their own for decades. The Hollywood star is still in a hurry to take some]","[, a major era in American comedy, and a rise in traditional Hollywood comedy has largely resulted in a boom]",max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 147.81692504882812\nbeam: 56.5164680480957\ntop k: 107.35860443115234\ntop p: 76.3049087524414,Have you heard the one about the computer programmer who bought a failing comedy club in Texas and turned it into a million dollar a year business?,"{'rouge1': 0.15384615384615383, 'rouge2': 0.0, 'rougeL': 0.10256410256410256, 'rougeLsum': 0.10256410256410256}","{'rouge1': 0.3111111111111111, 'rouge2': 0.0930232558139535, 'rougeL': 0.26666666666666666, 'rougeLsum': 0.26666666666666666}","{'rouge1': 0.15999999999999998, 'rouge2': 0.0, 'rougeL': 0.15999999999999998, 'rougeLsum': 0.15999999999999998}","{'rouge1': 0.2608695652173913, 'rouge2': 0.0, 'rougeL': 0.21739130434782608, 'rougeLsum': 0.21739130434782608}","{'precision': [0.8373798727989197], 'recall': [0.8194937705993652], 'f1': [0.8283402323722839], 'hashcode': 'roberta-large_L17_no-idf_version=0.3.12(hug_trans=4.50.0)'}","{'precision': [0.8780032992362976], 'recall': [0.8383058309555054], 'f1': [0.8576955199241638], 'hashcode': 'roberta-large_L17_no-idf_version=0.3.12(hug_trans=4.50.0)'}","{'precision': [0.8158785104751587], 'recall': [0.8173388242721558], 'f1': [0.8166080117225647], 'hashcode': 'roberta-large_L17_no-idf_version=0.3.12(hug_trans=4.50.0)'}","{'precision': [0.8390401005744934], 'recall': [0.8244628310203552], 'f1': [0.8316876292228699], 'hashcode': 'roberta-large_L17_no-idf_version=0.3.12(hug_trans=4.50.0)'}"
8,Relieved that the giant telecoms company would not be broken up they piled into the shares sending them up 3% in early trading.\nBT dodged a bullet - and as the chief executive of Ofcom Sharon Whi...,[of BT's pension scheme. of BT's pension scheme. of BT's pension scheme. of],"[of BT's giant pension scheme, Openreach, is a company that has fought in the courts to preserve and win]","[by shareholders who would support the ""golden share"" of Openreach would be on the rise in the next 12 months - as]",[BT to break the pensions from BT's existing private company Openreach.],max_length: 30\nnum_beams: 5\ntop_k: 50\ntop_p: 0.95,greedy: 14.837325096130371\nbeam: 119.41099548339844\ntop k: 95.8749771118164\ntop p: 552.5446166992188,"The reaction from BT's investors told us much about media regulator Ofcom's ruling on the fate of Openreach, the BT subsidiary that provides much of the UK's broadband infrastructure.","{'rouge1': 0.2916666666666667, 'rouge2': 0.043478260869565216, 'rougeL': 0.25, 'rougeLsum': 0.25}","{'rouge1': 0.23076923076923075, 'rouge2': 0.039999999999999994, 'rougeL': 0.19230769230769232, 'rougeLsum': 0.19230769230769232}","{'rouge1': 0.22641509433962265, 'rouge2': 0.0784313725490196, 'rougeL': 0.18867924528301888, 'rougeLsum': 0.18867924528301888}","{'rouge1': 0.2727272727272727, 'rouge2': 0.09523809523809523, 'rougeL': 0.22727272727272727, 'rougeLsum': 0.22727272727272727}","{'precision': [0.8571329712867737], 'recall': [0.8351439833641052], 'f1': [0.8459956049919128], 'hashcode': 'roberta-large_L17_no-idf_version=0.3.12(hug_trans=4.50.0)'}","{'precision': [0.8757728338241577], 'recall': [0.8726393580436707], 'f1': [0.8742033243179321], 'hashcode': 'roberta-large_L17_no-idf_version=0.3.12(hug_trans=4.50.0)'}","{'precision': [0.8496493697166443], 'recall': [0.865215539932251], 'f1': [0.8573617935180664], 'hashcode': 'roberta-large_L17_no-idf_version=0.3.12(hug_trans=4.50.0)'}","{'precision': [0.8829525113105774], 'recall': [0.8684666156768799], 'f1': [0.8756496906280518], 'hashcode': 'roberta-large_L17_no-idf_version=0.3.12(hug_trans=4.50.0)'}"